# Site settings
title: "All Things Git"
subtitle: The podcast about Git
author: Edward Thomson and Martin Woodward
email: podcast@allthingsgit.com
description: The podcast about Git.
long_description: |
  The podcast about Git.  Edward Thomson and Martin Woodward talk to the
  people who build Git, build tools for it and make their teams successful
  using it.

baseurl: "/"
url: "http://www.allthingsgit.com"

twitter_username: allthingsgit
github_username:  allthingsgit

gems:
 - jekyll-paginate

safe: false

# Pagination
paginate: 10
paginate_path: "/archives/page:num/"

# Build settings
permalink: none

include: [".htaccess"]
exclude:
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: inline
    css: class
    coderay_line_numbers: inline
    coderay_css: class

tag_title_prefix: "Entries Tagged "

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

